import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from "next/font/local";



const poppins = Poppins({
  weight:["100","200","300","400","500","600","800"]
})

export const fontBangla = localFont({
  src: "../../public/fonts/mayaboti-normal.ttf",
  weight: "400",
  style: "normal",
  display: "swap",
})

export const metadata = {
  title: {
    default: "Toys Shop - Your one-stop shop for kids",
    template:"%s | Toys Shop"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} antialiased`}
    >
      <body >

        <header className="py-4 md:w-11/12 mx-auto">
           <Navbar></Navbar>
        </header>

        <main  className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-302px)]">
               {children}
        </main>
      

        <footer>
         <Footer></Footer>
        </footer>


      </body>
    </html>
  );
}
